development:
  dialect: postgres
  database: tasks_development
  user: postgres
  password: postgres
  host: {{envOr "POSTGRES_HOST" "127.0.0.1"}}
  pool: 5

test:
  dialect: postgres
  database: tasks_test
  user: postgres
  password: postgres
  host: {{envOr "POSTGRES_HOST" "127.0.0.1"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/tasks_production?sslmode=disable"}}