name: Tasks Kata

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: gobuffalo/buffalo:v0.16.5

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...
        env: 
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on

      - name: Test
        run: buffalo test ./... -v
        env:
          POSTGRES_HOST: postgres
          GO111MODULE: on